//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs_proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class emps
    {
        public int ID_employee { get; set; }
        public string first_name_emp { get; set; }
        public string name_emp { get; set; }
        public string last_name_emp { get; set; }
        public Nullable<System.DateTime> birth_emp { get; set; }
        public string gender_emp { get; set; }
        public string post_emp { get; set; }
        public string email_emp { get; set; }
        public string passw_emp { get; set; }
        public byte[] photo_prof { get; set; }
    }
}
