//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs_proj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iccEntities_new : DbContext
    {
        public iccEntities_new()
            : base("name=iccEntities_new")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<emps> emps { get; set; }
        public virtual DbSet<mpr> mpr { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<partners> partners { get; set; }
        public virtual DbSet<reports> reports { get; set; }
    }
}
