//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs_proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class mpr
    {
        public int ID_mrp { get; set; }
        public string name_mrp { get; set; }
        public Nullable<System.DateTime> date_mrp { get; set; }
        public string opic_mrp { get; set; }
        public string categ_mrp { get; set; }
        public byte[] photo_mrp { get; set; }
    }
}
