//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs_proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class partners
    {
        public int ID_partn { get; set; }
        public string first_name_partn { get; set; }
        public string name_partn { get; set; }
        public string last_name_partn { get; set; }
        public Nullable<System.DateTime> birth_partn { get; set; }
        public string gender_partn { get; set; }
        public string company { get; set; }
        public string post_partn { get; set; }
        public string email_partn { get; set; }
        public string phone { get; set; }
        public byte[] photo_pr { get; set; }
    }
}
