//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs_proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class reports
    {
        public int ID_report { get; set; }
        public string name_report { get; set; }
        public Nullable<System.DateTime> date_rep { get; set; }
        public string categ_rep { get; set; }
        public byte[] file_rep { get; set; }
    }
}
